name: him5
description: "E-commerce Flutter app with Clean Architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.1
  get_it: ^7.6.0
  dio: ^5.3.1
  equatable: ^2.0.5
  cached_network_image: ^3.3.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
